# -*- coding: utf-8 -*-
"""Task-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qgDk8VtIEskHE5KN6mvSmyqJmlHYJBnx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AAPL.csv")

df.head()

df.info()

df.shape

df.shape

df.isnull()

df.duplicated()

print( df["Open"].mean())
print( df["Close"].mean())

df["Daily_return"] = ((df["Close"] - df["Open"]) / df["Open"]) * 100

df

