# -*- coding: utf-8 -*-
"""Task-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZazfOFA3mA-trlZHaOXa6f75RMr-gkTB
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AAPL.csv")

df["Date"] = pd.to_datetime(df["Date"])

df = df.sort_values("Date")

df.head()

plt.figure(figsize=(16, 8))

plt.plot(df.index, df["Open"], label="Open")
plt.plot(df.index, df["High"], label="High")
plt.plot(df.index, df["Low"], label="Low")
plt.plot(df.index, df["Close"], label="Close")

plt.title("OHLC Prices over time")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(16,8))
plt.plot(df["Date"],df["Volume"])
plt.title("Trading Volume Over Time")
plt.xlabel("Date")
plt.ylabel("Volume")
plt.show()

df["MA20"] = df["Close"].rolling(window=20).mean()

df["MA50"] = df["Close"].rolling(window=50).mean()

plt.figure(figsize=(12, 6))

plt.plot(df.index, df["Close"], label="Daily Close")
plt.title("closing price trend")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(12, 6))

plt.plot(df.index, df["MA20"], label="20-Day MA")

plt.title(" Moving Averages for short term")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(12, 6))

plt.plot(df.index, df["MA50"], label="50-Day MA")

plt.title("Moving Averages for long term")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(12, 6))

plt.plot(df.index, df["Close"], label="Daily Close")
plt.plot(df.index, df["MA20"], label="20-Day Moving Average")
plt.plot(df.index, df["MA50"], label="50-Day Moving Average")
plt.title("Closing Price with Moving Averages")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

