# -*- coding: utf-8 -*-
"""Task-7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186NGFYmwYrOu-m5xh2xpVLLRVr5W9Mkn
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/healthcare_dataset (2).csv')

df.head()

df.isnull().sum()

df.shape

df.columns

df.dtypes

df.info()

categorical_features = [
    'Gender',
    'Blood Type',
    'Medical Condition',
    'Insurance Provider',
    'Admission Type',
    'Medication',
    'Test Results'
]

for col in categorical_features:
    df[col] = df[col].str.strip()

numeric_columns = [
    'Age',
    'Billing Amount',
    'Room Number'
]

print("\nstatistical measures:")

for column in numeric_columns:
  print(f"\n{column}")
  print("Mean:",df[column].mean())
  print("Median:",df[column].median())
  print("Standard Deviation:",df[column].std())
  print("Q1:",df[column].quantile(0.25))
  print("Q2",df[column].quantile(0.50))
  print("Q3",df[column].quantile(0.75))

