# -*- coding: utf-8 -*-
"""Task-5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lX_yrcKA13Ea_6UoC6iN_8edxGUcgcZr
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as snd

df=pd.read_csv("/content/healthcare_dataset.csv")

df.head()

df.columns

df.shape

df.isnull().sum()

df['Medical_Code'].isnull().sum()

df['Discharge_Data']=(pd.to_datetime(df['Discharge_Date']))

df['Admission_Type'] = df['Admission_Type'].str.lower()

df.describe()

df['Admission_Data'] = pd.to_datetime(df['Admission_Date'], dayfirst=True)
df["Hospital_Stay_Dates"]=(df["Discharge_Data"]-df['Admission_Data']).dt.days
df["Hospital_Stay_Dates"].head()

df['Billing_Amount'].describe()

