# -*- coding: utf-8 -*-
"""Task-6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11RIVnFUC9VolU1G7TJdOY9FXpRFI5QtV
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sm

df = pd.read_csv('/content/healthcare_dataset (1).csv')

df.head()

df.isnull().sum()

df.shape

df.describe()

billing = df.groupby(["Medical Condition", "Insurance Provider"])["Billing Amount"].sum()
billing

df["stay Duration"] = (
    df["Discharge Date"] - df["Date of Admission"]
).dt.days
df.head()

plt.figure(figsize=(10,6))

data = df.groupby(
    ["Medical Condition", "Insurance Provider"]
)["Billing Amount"].mean().unstack()

# Bar chart
data.plot(
    kind="bar",
    stacked=True,
    figsize=(12, 6)
)

plt.title("Average Billing Amount by Medical Condition and Insurance Provider")
plt.xlabel("Medical Condition")
plt.ylabel("Average Billing Amount")
plt.xticks(rotation=45)
plt.legend(title="Insurance Provider")

plt.tight_layout()
plt.show()

plt.figure(figsize=(12,6))

sm.violinplot(
    data=df,
    x="Medical Condition",
    y="Billing Amount"
)

plt.title("Billing Amount Distribution by Medical Condition")
plt.xlabel("Medical Condition")
plt.ylabel("Billing Amount")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,6))

sm.violinplot(
    data=df,
    x="Insurance Provider",
    y="Billing Amount"
)

plt.title("Billing Amount Distribution by Insurance Provider")
plt.xlabel("Insurance Provider")
plt.ylabel("Billing Amount")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

df['Admission Month'] = df['Date of Admission'].dt.to_period('M')
monthly_admissions = df['Admission Month'].value_counts().sort_index()

plt.figure(figsize=(12,6))
monthly_admissions.plot(kind="line",marker="o")
plt.title("Monthly patient Admissions")
plt.xlabel('Month')
plt.ylabel('Number of Admissions')
plt.grid(True)
plt.tight_layout()
plt.show()

correlation_matrix = df[['Age', 'stay Duration', 'Billing Amount']].corr()

sm.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()